### ISSUE TITLE
Passing multiple groupings to `getPosteriorResponseRate`

### ISSUE THREAD

**Issue by thebioengineer** [RGLab/MIMOSA#10]
Currently `getPosteriorResponseRate()` limits the number of grouping variables to one. However, it would be nice if it was possible to pass multiple grouping variables (for example, visit and treatment). Currently if I want to pull out multiple, I would need to combine the two before passing into ConstructMIMOSAExpressionSet, and follow it through.

**Comment by gfinak** [comment]
Fixed in  50d7dbd
